CREATE DATABASE IF NOT EXISTS PROJETOPDO;

USE PROJETOPDO;

CREATE TABLE IF NOT EXISTS ARTISTA(
    ID_ART INT PRIMARY KEY AUTO_INCREMENT,
    NOME_ART VARCHAR(255) NOT NULL,
    GENERO_PRINCIPAL VARCHAR(255) NOT NULL,
    ANO_FORMACAO SMALLINT NOT NULL,
    DATA_NASCIMENTO DATE 
);

CREATE TABLE IF NOT EXISTS MUSICA(
    ID_MUS INT PRIMARY KEY AUTO_INCREMENT,
    TITULO_MUS VARCHAR(255) NOT NULL,
    DURACAO_MUS TIME NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    GENERO_MUS VARCHAR(255) 
);
